# Generated by Django 4.2.7 on 2025-09-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_from_technician'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_code', models.CharField(help_text='Unique equipment code/part number', max_length=100, unique=True)),
                ('brand_name', models.CharField(help_text='Brand name of the equipment', max_length=255)),
                ('equipment_name', models.CharField(help_text='Full name/model of the equipment', max_length=255)),
                ('equipment_type', models.CharField(choices=[('AC_UNIT', 'Air Conditioning Unit'), ('HEAT_PUMP', 'Heat Pump'), ('FURNACE', 'Furnace'), ('BOILER', 'Boiler'), ('THERMOSTAT', 'Thermostat'), ('DUCTWORK', 'Ductwork'), ('VENTILATION', 'Ventilation System'), ('REFRIGERANT', 'Refrigerant'), ('FILTER', 'Filter'), ('OTHER', 'Other')], default='AC_UNIT', help_text='Type of equipment', max_length=50)),
                ('model_number', models.CharField(blank=True, help_text='Model number of the equipment', max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, help_text='Serial number of the equipment', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the equipment', null=True)),
                ('specifications', models.JSONField(blank=True, help_text='Technical specifications (JSON format)', null=True)),
                ('capacity', models.CharField(blank=True, help_text='Capacity (e.g., BTU, tons, CFM)', max_length=100, null=True)),
                ('voltage', models.CharField(blank=True, help_text='Voltage requirements', max_length=50, null=True)),
                ('refrigerant_type', models.CharField(blank=True, help_text='Type of refrigerant used', max_length=100, null=True)),
                ('seer_rating', models.CharField(blank=True, help_text='SEER rating for efficiency', max_length=50, null=True)),
                ('warranty_period', models.CharField(blank=True, help_text='Warranty period (e.g., 5 years, 10 years)', max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, help_text='Date when equipment was purchased', null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price of the equipment', max_digits=10, null=True)),
                ('supplier', models.CharField(blank=True, help_text='Supplier or vendor name', max_length=255, null=True)),
                ('location', models.CharField(blank=True, help_text='Current location of the equipment', max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Under Maintenance'), ('RETIRED', 'Retired')], default='ACTIVE', help_text='Current status of the equipment', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the equipment is active in the system')),
                ('image', models.ImageField(blank=True, help_text='Image of the equipment', null=True, upload_to='equipment_images/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the equipment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['brand_name', 'equipment_name'],
            },
        ),
    ]
