# Generated by Django 4.2.7 on 2025-09-30 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_equipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['brand', 'full_name'], 'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['title'], 'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.AlterModelOptions(
            name='technician',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Technician', 'verbose_name_plural': 'Technicians'},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_code',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_name',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_type',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='refrigerant_type',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='seer_rating',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='voltage',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='warranty_period',
        ),
        migrations.RemoveField(
            model_name='site',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='site',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='site',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='site',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='specialization',
        ),
        migrations.AddField(
            model_name='client',
            name='code_client',
            field=models.CharField(default='CLIENT_001', help_text='Unique client code', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when the client account was created', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo of the company', null=True, upload_to='client_logos/'),
        ),
        migrations.AddField(
            model_name='client',
            name='social_media_link',
            field=models.URLField(blank=True, help_text="Link to client's social media page(s)", null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='status_juridique',
            field=models.CharField(choices=[('SNC', 'SNC (Société en Nom Collectif)'), ('SAEL', 'SAEL (Société par Actions à Responsabilité Limitée)'), ('EURL', 'EURL (Entreprise Unipersonnelle à Responsabilité Limitée)'), ('SA', 'SA (Société Anonyme)'), ('SPA', 'SPA (Société par Actions)')], default='SNC', help_text='Type of company', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone1',
            field=models.CharField(default='0000000000', help_text='Primary phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone2',
            field=models.CharField(blank=True, help_text='Secondary phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, help_text="Client's website", null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='brand',
            field=models.CharField(default='Generic', help_text='Manufacturer/brand (e.g., Samsung, LG, Daikin)', max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='client',
            field=models.ForeignKey(default=10121997, help_text='Client who owns this equipment', on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='core.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='code',
            field=models.CharField(default='EQ001', help_text='Unique equipment code', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='full_name',
            field=models.CharField(default='Air Conditioning Unit', help_text="Full descriptive name (e.g., 'Split AC Samsung 18000 BTU')", max_length=255),
        ),
        migrations.AddField(
            model_name='equipment',
            name='warranty_expiry',
            field=models.DateField(default='2025-12-31', help_text='Date when warranty ends'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='year_of_facturation',
            field=models.PositiveIntegerField(default=2024, help_text='Year the equipment was purchased/invoiced'),
        ),
        migrations.AddField(
            model_name='site',
            name='city',
            field=models.CharField(default='Algiers', help_text='City', max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='country',
            field=models.CharField(default='Algeria', help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude coordinate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude coordinate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='nif',
            field=models.CharField(default='NIF000000000', help_text='Fiscal identification number', max_length=50),
        ),
        migrations.AddField(
            model_name='site',
            name='nis',
            field=models.CharField(default='NIS000000000', help_text='Statistical identification number', max_length=50),
        ),
        migrations.AddField(
            model_name='site',
            name='number_of_workers',
            field=models.CharField(choices=[('<10', 'Less than 10 workers'), ('20-50', '20 to 50 workers'), ('>50', 'More than 50 workers')], default='<10', help_text='Number of workers at this site', max_length=10),
        ),
        migrations.AddField(
            model_name='site',
            name='postal_code',
            field=models.CharField(default='16000', help_text='Postal code', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='rc',
            field=models.CharField(default='RC000000000', help_text='Commercial register number', max_length=50),
        ),
        migrations.AddField(
            model_name='site',
            name='region',
            field=models.CharField(default='North', help_text='Region', max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='sector',
            field=models.CharField(default='Commercial', help_text='Sector', max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='title',
            field=models.CharField(default='Site Title', help_text='Name/title of the site', max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='wilaya',
            field=models.CharField(default='Algiers', help_text='Region/province', max_length=100),
        ),
        migrations.AddField(
            model_name='technician',
            name='date_of_enrollment',
            field=models.DateField(default='2024-01-01', help_text='Date they joined the company'),
        ),
        migrations.AddField(
            model_name='technician',
            name='identification_number',
            field=models.CharField(default='TECH001', help_text='National or company ID', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='picture',
            field=models.ImageField(blank=True, help_text="Technician's profile photo", null=True, upload_to='technician_photos/'),
        ),
        migrations.AddField(
            model_name='technician',
            name='speciality',
            field=models.CharField(default='General Maintenance', help_text='Area of expertise (e.g., installation, maintenance, electrical, refrigeration)', max_length=255),
        ),
        migrations.AddField(
            model_name='technician',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('BUSY', 'Busy'), ('ON_BREAK', 'On Break'), ('NOT_WORKING', 'Not Working')], default='FREE', help_text='Current status of the technician', max_length=15),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, help_text='Equipment photo', null=True, upload_to='equipment_images/'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model_number',
            field=models.CharField(default='MODEL001', help_text='Manufacturer model code', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(default='SN000000001', help_text='Unique identifier (important for maintenance tracking)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.TextField(default='Address not specified', help_text='Physical address of the site'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='email',
            field=models.EmailField(blank=True, help_text="Technician's email address", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='technician',
            name='phone_number',
            field=models.CharField(default='0000000000', help_text="Technician's phone number", max_length=20),
        ),
    ]
