# Generated by Django 4.2.7 on 2025-09-30 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_update_models_to_specification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['brand', 'full_name'], 'verbose_name': 'Equipment Type', 'verbose_name_plural': 'Equipment Types'},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='warranty_expiry',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='year_of_facturation',
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the equipment', null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this equipment type is available'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='specifications',
            field=models.JSONField(blank=True, help_text='Technical specifications (JSON format)', null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.CharField(help_text='Manufacturer/brand (e.g., Samsung, LG, Daikin)', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='code',
            field=models.CharField(help_text='Unique equipment type code', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='full_name',
            field=models.CharField(help_text="Full descriptive name (e.g., 'Split AC Samsung 18000 BTU')", max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model_number',
            field=models.CharField(help_text='Manufacturer model code', max_length=255),
        ),
        migrations.CreateModel(
            name='ClientEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='Unique serial number (important for maintenance tracking)', max_length=255, unique=True)),
                ('year_of_facturation', models.PositiveIntegerField(help_text='Year the equipment was purchased/invoiced')),
                ('warranty_expiry', models.DateField(help_text='Date when warranty ends')),
                ('installation_date', models.DateField(blank=True, help_text='Date when equipment was installed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this equipment instance', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this equipment instance is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client who owns this equipment instance', on_delete=django.db.models.deletion.CASCADE, related_name='client_equipment', to='core.client')),
                ('equipment', models.ForeignKey(help_text='Type of equipment', on_delete=django.db.models.deletion.CASCADE, related_name='client_instances', to='core.equipment')),
                ('site', models.ForeignKey(blank=True, help_text='Site where this equipment is installed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='core.site')),
            ],
            options={
                'verbose_name': 'Client Equipment',
                'verbose_name_plural': 'Client Equipment',
                'ordering': ['client__name', 'equipment__brand', 'equipment__full_name'],
                'unique_together': {('client', 'serial_number')},
            },
        ),
    ]
