# Generated by Django 4.2.7 on 2025-09-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_equipment_restructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code_client',
            field=models.CharField(help_text='Unique client code', max_length=50, unique=True),
        ),
    ]
