# Generated by Django 4.2.7 on 2025-10-05 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_client_code_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the technician group', max_length=255)),
                ('specialty', models.CharField(choices=[('INSTALLATION', 'Installation'), ('MAINTENANCE', 'Maintenance'), ('REPAIR', 'Repair'), ('ELECTRICAL', 'Electrical'), ('REFRIGERATION', 'Refrigeration'), ('HVAC', 'HVAC Systems'), ('GENERAL', 'General Service'), ('EMERGENCY', 'Emergency Response')], default='GENERAL', help_text='Specialty focus of this group', max_length=50)),
                ('description', models.TextField(blank=True, help_text="Description of the group's purpose and responsibilities", null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BUSY', 'Busy - Working on Assignment'), ('ON_BREAK', 'On Break'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Under Maintenance')], default='ACTIVE', help_text='Current status of the group', max_length=20)),
                ('max_capacity', models.PositiveIntegerField(default=5, help_text='Maximum number of technicians allowed in this group')),
                ('current_assignment', models.CharField(blank=True, help_text='Current assignment or project the group is working on', max_length=500, null=True)),
                ('equipment_specialization', models.CharField(blank=True, help_text='Types of equipment this group specializes in', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef_technician', models.ForeignKey(blank=True, help_text='Lead technician/chef of this group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to='core.technician')),
                ('technicians', models.ManyToManyField(blank=True, help_text='Technicians belonging to this group', related_name='technician_groups', to='core.technician')),
            ],
            options={
                'verbose_name': 'Technician Group',
                'verbose_name_plural': 'Technician Groups',
                'ordering': ['name'],
            },
        ),
    ]
