# Generated by Django 4.2.7 on 2025-10-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_techniciangroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='identification_number',
            field=models.CharField(blank=True, help_text='National or company ID', max_length=50, null=True, unique=True),
        ),
    ]
