# Generated by Django 4.2.7 on 2025-10-05 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_technician_identification_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text="Client's email address for login", max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='password123', help_text="Client's password for login", max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='token',
            field=models.CharField(blank=True, help_text='Authentication token for client login', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User account for login access', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='site',
            name='nis',
            field=models.CharField(default='NIS000000000', help_text='Statyistical identification number', max_length=50),
        ),
    ]
