# Generated by Django 4.2.7 on 2025-10-16 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_client_email_client_password_client_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique contract code number', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Description of the contract')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Date when the contract was created')),
                ('starting_date', models.DateField(help_text='Date when the contract starts')),
                ('ending_date', models.DateField(help_text='Date when the contract ends')),
                ('contract_type', models.CharField(choices=[('INSTALLATION', 'Installation'), ('MAINTENANCE', 'Maintenance')], help_text='Type of contract (Installation or Maintenance)', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price of the contract', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the contract is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client this contract belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.client')),
                ('equipment', models.ManyToManyField(blank=True, help_text='Equipment covered by this contract', related_name='contracts', to='core.clientequipment')),
                ('site', models.ForeignKey(help_text='Site this contract is for', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.site')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-creation_date'],
            },
        ),
    ]
