# Generated by Django 4.2.7 on 2025-10-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='pdf_document',
            field=models.FileField(blank=True, help_text='PDF document for the contract', null=True, upload_to='contract_pdfs/'),
        ),
    ]
