# Generated by Django 4.2.7 on 2025-10-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contract_pdf_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PROCESSED', 'Processed'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('SCHEDULED', 'Scheduled'), ('FINISHED', 'Finished')], default='CREATED', help_text='Current status of the contract', max_length=20),
        ),
    ]
