# Generated by Django 4.2.7 on 2025-10-19 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contract_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_code', models.CharField(help_text='Unique action code number', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the action')),
                ('action_type', models.CharField(choices=[('INSTALLATION', 'Installation'), ('MAINTENANCE', 'Maintenance'), ('CHECKING', 'Checking'), ('CLEANING', 'Cleaning'), ('FIXING', 'Fixing'), ('INTERVENING', 'Intervening'), ('INSPECTING', 'Inspecting')], help_text='Type of action to be performed', max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ONGOING', 'Ongoing'), ('FINISHED', 'Finished')], default='CREATED', help_text='Current status of the action', max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Date when the action was created')),
                ('starting_date', models.DateField(help_text='Date when the action starts')),
                ('ending_date', models.DateField(help_text='Date when the action ends')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Priority level of the action', max_length=10)),
                ('estimated_duration', models.DurationField(blank=True, help_text='Estimated duration to complete the action', null=True)),
                ('actual_duration', models.DurationField(blank=True, help_text='Actual time taken to complete the action', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the action is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(help_text='Contract this action belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.contract')),
                ('equipment', models.ManyToManyField(blank=True, help_text='Equipment involved in this action', related_name='actions', to='core.clientequipment')),
                ('group', models.ForeignKey(blank=True, help_text='Team group assigned to handle this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_actions', to='core.teamgroup')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'ordering': ['-creation_date'],
            },
        ),
    ]
