# Generated by Django 4.2.7 on 2025-10-19 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_action_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Team group assigned to handle this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_actions', to='core.techniciangroup'),
        ),
    ]
