# Generated by Django 4.2.7 on 2025-10-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_change_action_group_to_technician_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='pdf_document_1',
            field=models.FileField(blank=True, help_text='Primary PDF document for the action', null=True, upload_to='action_pdfs/'),
        ),
        migrations.AddField(
            model_name='action',
            name='pdf_document_2',
            field=models.FileField(blank=True, help_text='Secondary PDF document for the action', null=True, upload_to='action_pdfs/'),
        ),
        migrations.AddField(
            model_name='action',
            name='pdf_document_3',
            field=models.FileField(blank=True, help_text='Additional PDF document for the action', null=True, upload_to='action_pdfs/'),
        ),
    ]
