# Generated by Django 4.2.7 on 2025-10-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_pdf_fields_to_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
