# Generated by Django 4.2.7 on 2025-10-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_action_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='prix_ht',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix HT (Price excluding tax)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='prix_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix TTC (Price including tax)', max_digits=10, null=True),
        ),
    ]
