# Generated by Django 4.2.7 on 2025-10-20 18:11

from django.db import migrations, models


def populate_prix_ht(apps, schema_editor):
    Contract = apps.get_model('core', 'Contract')
    for contract in Contract.objects.filter(prix_ht__isnull=True):
        # Copy total_price to prix_ht if prix_ht is null
        if hasattr(contract, 'total_price') and contract.total_price:
            contract.prix_ht = contract.total_price
            contract.save()
        else:
            # Set a default value for contracts without total_price
            contract.prix_ht = 0.00
            contract.save()


def reverse_populate_prix_ht(apps, schema_editor):
    # No need to reverse this operation
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_price_fields_to_contract'),
    ]

    operations = [
        migrations.RunPython(populate_prix_ht, reverse_populate_prix_ht),
        migrations.RemoveField(
            model_name='contract',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='contract',
            name='prix_ht',
            field=models.DecimalField(decimal_places=2, help_text='Prix HT (Price excluding tax)', max_digits=10),
        ),
    ]
