# Generated by Django 4.2.7 on 2025-10-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_total_price_and_make_prix_ht_required'),
        ('core', '0022_populate_prix_ht_from_total_price'),
    ]

    operations = [
    ]
