# Generated by Django 4.2.7 on 2025-10-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_20251020_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='site',
        ),
        migrations.AddField(
            model_name='contract',
            name='sites',
            field=models.ManyToManyField(blank=True, help_text='Sites this contract covers', related_name='contracts', to='core.site'),
        ),
    ]
