# Generated by Django 4.2.7 on 2025-10-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_contract_site_contract_sites'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(help_text='Unique project code', max_length=50, unique=True)),
                ('project_name', models.CharField(help_text='Name of the installation project', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the project')),
                ('date_creation', models.DateField(auto_now_add=True, help_text='Date when project was created')),
                ('start_date', models.DateField(help_text='Project start date')),
                ('finish_date', models.DateField(help_text='Project finish date')),
                ('complexity', models.CharField(choices=[('SIMPLE', 'Simple'), ('NORMAL', 'Normal'), ('COMPLEX', 'Complex')], default='NORMAL', help_text='Project complexity level', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the project is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client for this project', on_delete=django.db.models.deletion.CASCADE, related_name='installation_projects', to='core.client')),
                ('contract', models.ForeignKey(blank=True, help_text='Associated contract (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_projects', to='core.contract')),
                ('equipment', models.ManyToManyField(blank=True, help_text='Equipment for this project', related_name='installation_projects', to='core.clientequipment')),
            ],
            options={
                'verbose_name': 'Project Installation',
                'verbose_name_plural': 'Project Installations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInstallationPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(help_text='PDF document', upload_to='project_installation_pdfs/')),
                ('title', models.CharField(help_text='Title/description of this PDF', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Project this PDF belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pdf_documents', to='core.projectinstallation')),
            ],
            options={
                'verbose_name': 'Project Installation PDF',
                'verbose_name_plural': 'Project Installation PDFs',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
