# Generated by Django 4.2.7 on 2025-10-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_projectinstallation_projectinstallationpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinstallation',
            name='sites',
            field=models.ManyToManyField(blank=True, help_text='Sites for this project', related_name='installation_projects', to='core.site'),
        ),
    ]
