# Generated by Django 4.2.7 on 2025-10-21 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_projectinstallation_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinstallation',
            name='technician_group',
            field=models.ForeignKey(blank=True, help_text='Technician group responsible for this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_projects', to='core.techniciangroup'),
        ),
    ]
