# Generated by Django 4.2.7 on 2025-10-22 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_technician_group_to_project_installation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the traveaux', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the traveaux')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Total quantity to be completed')),
                ('quantity_completed', models.PositiveIntegerField(default=0, help_text='Quantity that has been completed')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ONGOING', 'Ongoing'), ('FINISHED', 'Finished')], default='CREATED', help_text='Current status of the traveaux', max_length=10)),
                ('estimated_time', models.DurationField(help_text='Estimated time to complete this traveaux')),
                ('scheduled_dates', models.JSONField(blank=True, help_text='Scheduled dates for this traveaux (JSON array of dates)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Project this traveaux belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='traveaux', to='core.projectinstallation')),
                ('sites', models.ManyToManyField(blank=True, help_text='Sites where this traveaux will be performed', related_name='traveaux', to='core.site')),
            ],
            options={
                'verbose_name': 'Traveaux',
                'verbose_name_plural': 'Traveaux',
                'ordering': ['-created_at'],
            },
        ),
    ]
