# Generated by Django 4.2.7 on 2025-10-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_traveaux'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInstallationQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(help_text='Quote PDF document', upload_to='project_installation_quotes/')),
                ('title', models.CharField(help_text='Title/description of this quote PDF', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Project this quote PDF belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='quote_pdfs', to='core.projectinstallation')),
            ],
            options={
                'verbose_name': 'Project Installation Quote',
                'verbose_name_plural': 'Project Installation Quotes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInstallationPV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(help_text='PV PDF document', upload_to='project_installation_pvs/')),
                ('title', models.CharField(help_text='Title/description of this PV PDF', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Project this PV PDF belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pv_pdfs', to='core.projectinstallation')),
            ],
            options={
                'verbose_name': 'Project Installation PV',
                'verbose_name_plural': 'Project Installation PVs',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInstallationFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(help_text='Facture PDF document', upload_to='project_installation_factures/')),
                ('title', models.CharField(help_text='Title/description of this facture PDF', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Project this facture PDF belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='facture_pdfs', to='core.projectinstallation')),
            ],
            options={
                'verbose_name': 'Project Installation Facture',
                'verbose_name_plural': 'Project Installation Factures',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
