# Generated by Django 4.2.7 on 2025-10-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_projectinstallationquote_projectinstallationpv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_duration_years',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of the contract in years (for maintenance contracts)', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='maintenance_frequency_per_year',
            field=models.PositiveIntegerField(blank=True, help_text='Number of maintenance visits per year (for maintenance contracts)', null=True),
        ),
    ]
