# Generated by Django 4.2.7 on 2025-10-28 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_contract_contract_duration_years_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(help_text='Unique project code', max_length=50, unique=True)),
                ('project_name', models.CharField(help_text='Name of the maintenance project', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the project')),
                ('date_creation', models.DateField(auto_now_add=True, help_text='Date when project was created')),
                ('start_date', models.DateField(help_text='Project start date')),
                ('finish_date', models.DateField(help_text='Project finish date')),
                ('complexity', models.CharField(choices=[('SIMPLE', 'Simple'), ('NORMAL', 'Normal'), ('COMPLEX', 'Complex')], default='NORMAL', help_text='Project complexity level', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the project is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client for this project', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_projects', to='core.client')),
                ('contract', models.ForeignKey(blank=True, help_text='Associated maintenance contract (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_projects', to='core.contract')),
                ('equipment', models.ManyToManyField(blank=True, help_text='Equipment for this project', related_name='maintenance_projects', to='core.clientequipment')),
                ('sites', models.ManyToManyField(blank=True, help_text='Sites for this project', related_name='maintenance_projects', to='core.site')),
                ('technician_group', models.ForeignKey(blank=True, help_text='Technician group responsible for this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_projects', to='core.techniciangroup')),
            ],
            options={
                'verbose_name': 'Project Maintenance',
                'verbose_name_plural': 'Project Maintenances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMaintenanceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(help_text='Quote PDF document', upload_to='project_maintenance_quotes/')),
                ('title', models.CharField(help_text='Title/description of this quote PDF', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Project this quote PDF belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='quote_pdfs', to='core.projectmaintenance')),
            ],
            options={
                'verbose_name': 'Project Maintenance Quote',
                'verbose_name_plural': 'Project Maintenance Quotes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMaintenancePV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(help_text='PV PDF document', upload_to='project_maintenance_pvs/')),
                ('title', models.CharField(help_text='Title/description of this PV PDF', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Project this PV PDF belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pv_pdfs', to='core.projectmaintenance')),
            ],
            options={
                'verbose_name': 'Project Maintenance PV',
                'verbose_name_plural': 'Project Maintenance PVs',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMaintenancePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(help_text='PDF document', upload_to='project_maintenance_pdfs/')),
                ('title', models.CharField(help_text='Title/description of this PDF', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Project this PDF belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pdf_documents', to='core.projectmaintenance')),
            ],
            options={
                'verbose_name': 'Project Maintenance PDF',
                'verbose_name_plural': 'Project Maintenance PDFs',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMaintenanceFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(help_text='Facture PDF document', upload_to='project_maintenance_factures/')),
                ('title', models.CharField(help_text='Title/description of this facture PDF', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Project this facture PDF belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='facture_pdfs', to='core.projectmaintenance')),
            ],
            options={
                'verbose_name': 'Project Maintenance Facture',
                'verbose_name_plural': 'Project Maintenance Factures',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTraveaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the traveaux', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the traveaux')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Total quantity to be completed')),
                ('quantity_completed', models.PositiveIntegerField(default=0, help_text='Quantity that has been completed')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ONGOING', 'Ongoing'), ('FINISHED', 'Finished')], default='CREATED', help_text='Current status of the traveaux', max_length=10)),
                ('estimated_time', models.DurationField(help_text='Estimated time to complete this traveaux')),
                ('scheduled_dates', models.JSONField(blank=True, help_text='Scheduled dates for this traveaux (JSON array of dates)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Project this traveaux belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_traveaux', to='core.projectmaintenance')),
                ('sites', models.ManyToManyField(blank=True, help_text='Sites where this traveaux will be performed', related_name='maintenance_traveaux', to='core.site')),
            ],
            options={
                'verbose_name': 'Maintenance Traveaux',
                'verbose_name_plural': 'Maintenance Traveaux',
                'ordering': ['-created_at'],
            },
        ),
    ]
