# Generated by Django 4.2.7 on 2025-10-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_maintenance_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='prix_ht',
            field=models.DecimalField(decimal_places=2, help_text='Prix HT (Price excluding tax)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='contract',
            name='prix_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix TTC (Price including tax)', max_digits=15, null=True),
        ),
    ]
