# Generated by Django 4.2.7 on 2025-10-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_contract_prix_ht_alter_contract_prix_ttc'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='create_project_maintenance_automatically',
            field=models.BooleanField(default=False, help_text='Automatically create maintenance projects when contract is created'),
        ),
    ]
