# Generated by Django 5.2.7 on 2025-11-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_contract_create_project_maintenance_automatically'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='model_number',
            field=models.CharField(blank=True, help_text='Manufacturer model code', max_length=255, null=True),
        ),
    ]
