# Generated by Django 4.2.7 on 2025-11-15 22:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_traveauxreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTraveauxReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the report', max_length=255)),
                ('report_file', models.FileField(help_text='PDF report document', upload_to='maintenance_traveaux_reports/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('traveaux', models.ForeignKey(help_text='Maintenance traveaux this report belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.maintenancetraveaux')),
            ],
            options={
                'verbose_name': 'Maintenance Traveaux Report',
                'verbose_name_plural': 'Maintenance Traveaux Reports',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
