# Generated by Django 4.2.7 on 2025-11-21 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_maintenancetraveauxreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='password',
            field=models.CharField(blank=True, default='123', help_text="Technician's password for login (default: 123)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User account for login access', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
