# Generated by Django 4.2.7 on 2025-11-30 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_technician_password_technician_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Expo push notification token', max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android'), ('WEB', 'Web')], default='ANDROID', help_text='Type of device', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technician', models.ForeignKey(help_text='Technician this device token belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='core.technician')),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
                'ordering': ['-created_at'],
                'unique_together': {('technician', 'token')},
            },
        ),
    ]
