# Generated by Django 4.2.7 on 2026-04-28 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_client_tax_ids_remove_from_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetraveaux',
            name='is_secondary',
            field=models.BooleanField(default=False, help_text='Whether this traveaux is a secondary task'),
        ),
        migrations.AddField(
            model_name='maintenancetraveaux',
            name='parent_traveaux',
            field=models.ForeignKey(blank=True, help_text='Parent traveaux when this is a secondary task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_traveaux', to='core.maintenancetraveaux'),
        ),
        migrations.AddField(
            model_name='traveaux',
            name='is_secondary',
            field=models.BooleanField(default=False, help_text='Whether this traveaux is a secondary task'),
        ),
        migrations.AddField(
            model_name='traveaux',
            name='parent_traveaux',
            field=models.ForeignKey(blank=True, help_text='Parent traveaux when this is a secondary task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_traveaux', to='core.traveaux'),
        ),
    ]
