# Generated by Django 4.2.7 on 2026-06-22 17:25

import django.core.validators
from django.contrib.auth.hashers import make_password
from django.db import migrations, models
import django.db.models.deletion


def bootstrap_organizations(apps, schema_editor):
    Organization = apps.get_model('core', 'Organization')
    User = apps.get_model('core', 'User')
    Client = apps.get_model('core', 'Client')
    Technician = apps.get_model('core', 'Technician')
    TechnicianGroup = apps.get_model('core', 'TechnicianGroup')
    TeamGroup = apps.get_model('core', 'TeamGroup')
    Equipment = apps.get_model('core', 'Equipment')

    main_org, _ = Organization.objects.get_or_create(
        slug='pika-main',
        defaults={'name': 'PIKA Main', 'is_active': True},
    )

    Client.objects.filter(organization__isnull=True).update(organization=main_org)
    Technician.objects.filter(organization__isnull=True).update(organization=main_org)
    TechnicianGroup.objects.filter(organization__isnull=True).update(organization=main_org)
    TeamGroup.objects.filter(organization__isnull=True).update(organization=main_org)
    Equipment.objects.filter(organization__isnull=True).update(organization=main_org)

    User.objects.filter(role='ADMIN', organization__isnull=True).update(organization=main_org)
    User.objects.filter(role='TECHNICIAN', organization__isnull=True).update(organization=main_org)
    User.objects.filter(is_superuser=True, organization__isnull=True).update(organization=main_org)

    trial_org, _ = Organization.objects.get_or_create(
        slug='test-admin1',
        defaults={'name': 'Test Admin 1 (Free Trial)', 'is_active': True},
    )

    if not User.objects.filter(username='test-admin1').exists():
        User.objects.create(
            username='test-admin1',
            email='test-admin1@pika.local',
            password=make_password('pikafreetrial2026'),
            role='ADMIN',
            is_staff=True,
            is_active=True,
            organization=trial_org,
        )


def unbootstrap_organizations(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Organization = apps.get_model('core', 'Organization')
    User.objects.filter(username='test-admin1').delete()
    Organization.objects.filter(slug__in=['test-admin1', 'pika-main']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_traveaux_progress_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization that owns this client record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.organization'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization that owns this equipment catalog entry', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_catalog', to='core.organization'),
        ),
        migrations.AddField(
            model_name='teamgroup',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization that owns this team group', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_groups', to='core.organization'),
        ),
        migrations.AddField(
            model_name='technician',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this technician belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='core.organization'),
        ),
        migrations.AddField(
            model_name='techniciangroup',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization that owns this technician group', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_groups', to='core.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this admin/staff user belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.organization'),
        ),
        migrations.RunPython(bootstrap_organizations, unbootstrap_organizations),
        migrations.AlterField(
            model_name='client',
            name='code_client',
            field=models.CharField(help_text='Unique client code within the organization', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text="Client's email address for login", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientequipment',
            name='serial_number',
            field=models.CharField(help_text='Serial number (unique per client equipment record)', max_length=255),
        ),
        migrations.AlterField(
            model_name='contract',
            name='code',
            field=models.CharField(help_text='Contract code', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='code',
            field=models.CharField(help_text='Equipment type code unique within the organization', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectinstallation',
            name='project_code',
            field=models.CharField(help_text='Project code unique within the organization', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectmaintenance',
            name='project_code',
            field=models.CharField(help_text='Project code unique within the organization', max_length=50),
        ),
        migrations.AlterField(
            model_name='technician',
            name='identification_number',
            field=models.CharField(blank=True, help_text='National or company ID', max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('organization', 'code_client'), name='uniq_client_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_equipment_code_per_org'),
        ),
    ]
